# syntax=docker/dockerfile:1
FROM node:20

WORKDIR /usr/src/app

COPY package*.json /usr/src/app

RUN yarn install

COPY . /usr/src/app

ARG VITE_APP_URL
ENV VITE_APP_URL ${VITE_APP_URL}

ARG VITE_API_URL
ENV VITE_API_URL ${VITE_API_URL}

ARG VITE_SENTRY_DSN
ENV VITE_SENTRY_DSN ${VITE_SENTRY_DSN}

ARG VITE_GOOGLE_API_KEY
ENV VITE_GOOGLE_API_KEY ${VITE_GOOGLE_API_KEY}

ARG VITE_STRIPE_PUBLISHABLE_KEY
ENV VITE_STRIPE_PUBLISHABLE_KEY ${VITE_STRIPE_PUBLISHABLE_KEY}

RUN yarn build

EXPOSE 4173

CMD ["yarn", "preview"]
